get:
  operationId: get_product_return_certificates
  tags:
    - Product Return
  summary: List Product Return Certificates
  description: >
    Get all product return certificates associated to a receipt's id.
  security:
    - BearerAuth: [ ]
  parameters:
    - name: receipt_id
      in: path
      required: true
      description: The receipt's id
      schema:
        type: number
  responses:
    200:
      description: List of product return certificates.
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: number
                  description: Id of the certificate.
                receipt_item_id:
                  type: number
                  description: Id of the associated receipt item.
                quantity:
                  type: number
                  description: Quantity of item returned.
                return_date:
                  type: string
                  description: Creation date of the certificate.
          example:
            - id: 1
              receipt_item_id: 12
              quantity: 2
              return_date: 2022-08-13T16:17:39.278Z

            - id: 2
              receipt_item_id: 4
              quantity: 1
              return_date: 2022-08-11T16:12:59.278Z
    400:
      $ref: '../../../../openapi.yaml#/components/responses/400'
    401:
      $ref: '../../../../openapi.yaml#/components/responses/401'
    500:
      $ref: '../../../../openapi.yaml#/components/responses/500'

post:
  operationId: post_product_return_certificates
  tags:
    - Product Return
  summary: Create Product Return Certificates
  description: >
    Create a product return certificate on a receipt item.
  security:
    - BearerAuth: [ ]
  parameters:
    - name: receipt_id
      in: path
      required: true
      description: The receipt's id
      schema:
        type: number
  requestBody:
    description: Certificate's informations.
    content:
      application/json:
        schema:
          type: object
          properties:
            receipt_item_id:
              type: number
            quantity:
              type: number
            reason:
              type: string
        example:
          receipt_item_id: 123
          quantity: 2
  responses:
    201:
      description: Product Return Certificate created.
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: number
                description: Id of the certificate.
              receipt_item_id:
                type: number
                description: Id of the associated receipt item.
              quantity:
                type: number
                description: Quantity of item returned.
              reason:
                type: string
                description: Reason of return.
              return_date:
                type: string
                description: Creation date of the certificate.
          example:
            id: 2
            receipt_item_id: 123
            quantity: 2
            return_date: 2022-08-11T16:12:59.278Z
    400:
      $ref: '../../../../openapi.yaml#/components/responses/400'
    401:
      $ref: '../../../../openapi.yaml#/components/responses/401'
    500:
      $ref: '../../../../openapi.yaml#/components/responses/500'
