openapi: "3.0.2"
info:
  x-logo:
    url: "https://avatars.githubusercontent.com/u/72045151?s=400&u=2da454a65a925719805331f9e3993bec4bc0b417&v=4"
  title: Pizzi API - Ressource server
  version: "0.1.0"
  description: >
    This is the internal API resource server documentation for the PizziPayment.
    You can find out more about Pizzi [here](https://www.pizzi-payment.fr).
  contact:
    email: contact@pizzi-payment.fr

servers:
  - description: localhost
    url: http://localhost:5000

tags:
  - name: Shop
    description: Everything about shop.

  - name: User
    description: Everything about user.

paths:
  /users:
    $ref: './components/endpoints/authentication/user.yaml'
  /shops:
    $ref: './components/endpoints/authentication/shop.yaml'

components:
  securitySchemes:
    $ref: './components/security/_index.yaml'
