openapi: "3.1.0"
info:
  x-logo:
    url: "https://avatars.githubusercontent.com/u/72045151?s=400&u=2da454a65a925719805331f9e3993bec4bc0b417&v=4"
  title: Pizzi API - Ressource server
  version: "0.1.0"
  description: >
    This is the internal API resource server documentation for the PizziPayment.
    You can find out more about Pizzi [here](https://www.pizzi-payment.fr).
  contact:
    email: contact@pizzi-payment.fr

servers:
  - description: localhost
    url: http://localhost:5000

tags:
  - name: Shop Item
    description: >
      Every route about a shop item. We call shop item product and service that
      a shop can sell.

  - name: Shop
    description: Everything about shop.

  - name: User
    description: Everything about user.

paths:
  /users:
    $ref: './components/endpoints/resource/user.yaml'
  /users/me/email:
    $ref: './components/endpoints/resource/user/email.yaml'
  /users/me/password:
    $ref: './components/endpoints/resource/user/password.yaml'
  /users/me/receipts:
    $ref: './components/endpoints/resource/user/receipts.yaml'
  /users/me/receipts/{id}:
    $ref: './components/endpoints/resource/user/receipt.yaml'

  /shops:
    $ref: './components/endpoints/resource/shop.yaml'
  /shops/me/email:
    $ref: './components/endpoints/resource/shop/email.yaml'
  /shops/me/password:
    $ref: './components/endpoints/resource/shop/password.yaml'
  /shops/me/items:
    $ref: './components/endpoints/resource/shop/item.yaml'
  /shops/me/items/{id}:
    $ref: './components/endpoints/resource/shop/item/id.yaml'
  /shops/me/receipts:
    $ref: './components/endpoints/resource/shop/receipts.yaml'
  /shops/me/receipts/{id}:
    $ref: './components/endpoints/resource/shop/receipt.yaml'

components:
  securitySchemes:
    $ref: './components/security/_index.yaml'
