openapi: "3.0.2"
info:
  x-logo:
    url: "https://avatars.githubusercontent.com/u/72045151?s=400&u=2da454a65a925719805331f9e3993bec4bc0b417&v=4"
  title: Pizzi API
  version: "pre-alpha"
  description: >
    This is the internal API documentation for Pizzi.
    You can find out more about Pizzi at [https://www.pizzi-payment.fr](https://www.pizzi-payment.fr).
  contact:
    email: contact@pizzi-payment.fr

servers:
  - description: localhost
    url: http://localhost:5000

tags:
  - name: Auth
    description: Everything about authentication.

  - name: Receipts
    description: Everything about receipts querying.

paths:
  /auth/user:
    $ref: './components/endpoints/authentication/user.yaml'
  /auth/shop:
    $ref: './components/endpoints/authentication/shop.yaml'
  /auth/user/login:
    $ref: './components/endpoints/authentication/login_user.yaml'
  /auth/shop/login:
    $ref: './components/endpoints/authentication/login_shop.yaml'
  /auth/disconnect:
    $ref: './components/endpoints/authentication/disconnect.yaml'

components:
  securitySchemes:
    $ref: './components/security/_index.yaml'
