name: Remove temporary PR documentation.
on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  push-temporary-docs:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ github.repository_owner }}/BackDocumentation
    defaults:
      run:
        working-directory: ./documentation
    steps:
      - name: Fetch the list of tags related to PR${{ github.event.number}}.
        run: |
          TAGS=$(
            gh release list --repo $REPOSITORY | \
            grep 'ResourceServer.PR${{ github.event.number }}' | \
            cut -f 1)

          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
          echo "TAGS<<EOF" >> $GITHUB_ENV
          echo "$TAGS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Delete list of release
        run: echo ${{ env.TAGS }} | xargs -I {} gh release delete {} --repo $REPOSITORY --yes
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Delete tags from BackDocumentation repo
        run: echo ${{ env.TAGS }} | xargs -I {} git push https://Pizzi-token:${{ secrets.ACCESS_TOKEN }}@github.com/$REPOSITORY --delete {}
