name: Deploy doc
on:
  repository_dispatch:

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - name:
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: PizziPayment/PizziPayment.github.io
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: Trigger documentation build workflow
          client-payload: '{ "repo": "resource-server" }'
