name: Deploy doc
on:
  repository_dispatch:

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - name: 'Dispatch action to deploy the documentation'
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: PizziPayment/PizziPayment.github.io
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: Trigger resource-server documentation build workflow
          client-payload: '{ "repo": "resource-server", "branch": "${{ github.ref_name }}" }'
