name: Deploy doc
on:
  repository_dispatch:

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST https://api.github.com/repos/PizziPayment/PiziPayment.github.io/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          --data '{ "event_type": "update" }'
