name: Check doc
on:
  push:
    branches:
      - 'develop'
      - 'master'
      - 'jest-workflow-integration'

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registery-url: 'https://pointecouteau.fr:40403/'
          cache: 'yarn'
      - name: Install dependencies.
        run: yarn install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${VERDACIO_TOKEN}
      - uses: actions/checkout@v2
        with:
          repository: PizziPayment/PizziBackDeploymentTools
          ref: master
          path: db
      - name: Create database.
        run: cd db && docker compose up db -d
      - name: Run jest tests.
        run: yarn run test
