name: jest
on:
  pull_request:
    branches:
      - 'develop'
      - 'master'

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'yarn'
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DB_DEPLOY_KEY }}
      - name: Install dependencies.
        run: yarn install
      - uses: actions/checkout@v2
        with:
          repository: PizziPayment/PizziBackDeploymentTools
          ref: master
          path: db
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Create database.
        run: cd db && docker compose up db -d
      - name: Run jest tests.
        run: yarn run test
