name: Create temporary PR documentation.
on:
  pull_request:
    branches:
      - develop

jobs:
  push-temporary-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./documentation
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Install documentation tools
        run: yarn install
      - name: Build documentation
        run: yarn run builder

      - name: Rename documentation with commit sha
        run: mv index.html 'index-${{ github.sha }}.html'

      - name: publish doc
        uses: ncipollo/release-action@v1
        with:
          repo: BackDocumentation
          artifacts: "documentation/index-${{ github.sha }}.html"
          token: ${{ secrets.ACCESS_TOKEN }}
          tag: ResourceServer.PR${{ github.event.number }}
          omitName: true

      - name: Add documentation as comment to PR
        uses: allthatjazzleo/actions-pull-request-add-comment@master
        with:
          message: >
            "Documentation for commit ${{ github.sha }} available [here]
            (https://github.com/PizziPayment/BackDocumentation/releases/download/ResourceServer.PR${{ github.event.number }}/index-${{ github.sha }}.html)."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
