name: Create temporary PR documentation.
on:
  pull_request:
    branches:
      - develop

jobs:
  push-temporary-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./documentation
    env:
      DOC_SUB_FOLDER: ResourceServer/doc
      PR_NUMBER: ${{ github.event.number }}
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Install documentation tools
        run: yarn install
      - name: Build documentation
        run: yarn run builder

      - name: publish doc
        uses: ncipollo/release-action@v1
        with:
          repo: BackDocumentation
          artifacts: "documentation/index.html"
          token: ${{ secrets.ACCESS_TOKEN }}
          tag: $PR_NUMBER.$COMMIT_SHA
          omitName: true
