name: Create temporary PR documentation.
on:
  pull_request:
    branches:
      - develop

jobs:
  push-temporary-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./documentation
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Install documentation tools
        run: yarn install
      - name: Build documentation
        run: yarn run builder

      - name: publish doc
        uses: ncipollo/release-action@v1
        with:
          repo: BackDocumentation
          artifacts: "documentation/index.html"
          token: ${{ secrets.ACCESS_TOKEN }}
          tag: ResourceServer.PR${{ github.event.number }}-${{ github.sha }}
          omitName: true
